/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/models/samurai.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/samurai.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Arm_L.geometry} material={materials.Mat_Black} position={[-0.35, 1.36, 0]} scale={[0.12, 0.44, 0.12]} />
      <mesh geometry={nodes.Arm_R.geometry} material={materials.Mat_Black} position={[0.36, 1.32, 0]} scale={[0.12, 0.22, 0.12]} />
      <mesh geometry={nodes.ChestPlate.geometry} material={materials.Mat_Red} position={[0, 1.28, 0.15]} rotation={[-0.04, 0, 0]} scale={[0.38, 0.4, 0.05]} />
      <mesh geometry={nodes.CyberVisor.geometry} material={materials.Mat_Red_Glow} position={[0, 1.76, 0.16]} scale={[0.28, 0.05, 0.12]} />
      <mesh geometry={nodes.Forearm_R.geometry} material={materials.Mat_Black} position={[0.36, 1.04, 0.02]} scale={[0.11, 0.24, 0.11]} />
      <mesh geometry={nodes.Head.geometry} material={materials.Mat_White} position={[0, 1.74, 0]} scale={0.22} />
      <mesh geometry={nodes.Leg_L.geometry} material={materials.Mat_DarkGray} position={[-0.15, 0.6, 0]} scale={[0.18, 0.55, 0.24]} />
      <mesh geometry={nodes.Leg_R.geometry} material={materials.Mat_DarkGray} position={[0.15, 0.6, 0]} scale={[0.18, 0.55, 0.24]} />
      <mesh geometry={nodes.ObiBelt.geometry} material={materials.Mat_DarkGray} position={[0, 0.98, 0.01]} scale={[0.52, 0.1, 0.3]} />
      <mesh geometry={nodes.ObiKnot.geometry} material={materials.Mat_Red} position={[0, 0.98, 0.16]} scale={[0.2, 0.12, 0.02]} />
      <mesh geometry={nodes.ShoulderArmor_L.geometry} material={materials.Mat_Red} position={[-0.32, 1.44, 0]} rotation={[0, 0, -0.25]} scale={[0.14, 0.25, 0.32]} />
      <mesh geometry={nodes.ShoulderArmor_R.geometry} material={materials.Mat_Red} position={[0.32, 1.44, 0]} rotation={[0, 0, 0.25]} scale={[0.14, 0.25, 0.32]} />
      <mesh geometry={nodes.StrawHat.geometry} material={materials.Mat_DarkGray} position={[0, 1.95, 0]} rotation={[-0.08, 0, 0]} scale={[0.54, 0.15, 0.54]} />
      <mesh geometry={nodes.SwordBlade.geometry} material={materials.Mat_Silver} position={[0.42, 1.55, 0.22]} rotation={[-0.539, -0.226, -0.133]} scale={[0.015, 1, 0.04]} />
      <mesh geometry={nodes.SwordGuard.geometry} material={materials.Mat_Silver} position={[0.42, 1, 0.12]} rotation={[-0.539, -0.226, -0.133]} scale={[0.05, 0.02, 0.05]} />
      <mesh geometry={nodes.SwordHandle.geometry} material={materials.Mat_Red} position={[0.42, 0.88, 0.1]} rotation={[-0.539, -0.226, -0.133]} scale={[0.02, 0.22, 0.02]} />
      <mesh geometry={nodes.Torso.geometry} material={materials.Mat_Black} position={[0, 1.2, 0]} scale={[0.5, 0.7, 0.28]} />
    </group>
  )
}

useGLTF.preload('/samurai.glb')
